# Generated by Django 4.0.3 on 2022-04-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='rating',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
    ]
