# Generated by Django 4.0.3 on 2022-04-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_us_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='Contact',
        ),
    ]
