# Generated by Django 4.1.2 on 2023-01-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_contact_us_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='rating',
        ),
    ]
